---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: Durch ein Upgrade aller NetApp Storage-Komponenten können Sie Ihr SolidFire Element Storage-System nach der Implementierung auf dem neuesten Stand halten. 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= Übersicht der Aktualisierungssequenz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können das SolidFire Element Storage-System nach der Implementierung immer auf dem neuesten Stand halten, indem Sie alle NetApp Storage-Komponenten sequenziell aktualisieren.

Zu diesen Komponenten gehören Managementservices, NetApp Hybrid Cloud Control, Element Software, Management-Node und (je nach Installation) das Element Plug-in für vCenter Server.

[NOTE]
====
* Ab dem 2023. November können Sie ein Komponenten-Upgrade nicht mit NetApp Hybrid Cloud Control oder REST API starten, da die (privaten und öffentlichen) Signaturschlüsselzertifikate am 5. November 2023 abgelaufen sind. Sie können dieses Problem beheben, indem Sie die im Knowledge Base-Artikel dokumentierte Problemumgehung befolgen https://kb.netapp.com/onprem/solidfire/Element_OS/SolidFire_and_HCI_upgrades_unable_to_start_due_to_upgrade_package_upload_error["SolidFire- und HCI-Upgrades können nicht gestartet werden, da Fehler beim Hochladen der Upgradepakete aufgetreten ist"^].
* Ab Element 12.7 werden die Storage-Nodes SF2405 und SF9608 sowie FC0025 und SF-FCN-01 FC nicht unterstützt. Wenn Sie versuchen, einen dieser Knoten auf Element 12.7 zu aktualisieren, wird ein Fehler angezeigt, der angibt, dass dieser Knoten nicht von Element 12.7 unterstützt wird.
* Ab Element 12.5 werden NetApp HealthTools bei Upgrades der Element Software nicht mehr unterstützt. Bei Element 11.0 oder 11.1 müssen Sie zuerst https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Upgrade auf Element 12.3 mit HealthTools"^] und dann mithilfe von NetApp Hybrid Cloud Control auf Element 12.5 oder höher aktualisieren.


====
In den <<sys_upgrade,Systemaktualisierungssequenz>> Inhalten werden die Aufgaben beschrieben, die für ein Upgrade des SolidFire All-Flash-Storage-Systems erforderlich sind. Idealerweise werden diese Verfahren als Teil der größeren Aufrüstsequenz und nicht isoliert durchgeführt. Wenn ein komponentenbasiertes Upgrade oder eine Aktualisierung erforderlich ist, lesen Sie die Verfahrensvoraussetzungen, um sicherzustellen, dass zusätzliche Komplexität bewältigt wird.

Im link:task_sf_upgrade_all_vsphere.html["VSphere-Upgrade-Sequenz"]Inhalt des Including Element Plug-in for vCenter Server werden zusätzliche Schritte vor und nach dem Upgrade beschrieben, die zur Neuinstallation des Element Plug-ins für vCenter Server erforderlich sind.

.Was Sie benötigen
* Sie führen Management-Node 11.3 oder höher aus. Neuere Versionen des Management-Node verfügen über eine modulare Architektur, die individuelle Services zur Verfügung stellt.
+

TIP: Um die Version zu überprüfen, melden Sie sich bei Ihrem Management-Node an, und zeigen Sie die Versionsnummer des Elements im Anmeldebanner an. Wenn Sie nicht über 11.3 verfügen, siehe link:task_hcc_upgrade_management_node.html["Upgrade Ihres Management-Node"].

* Sie haben ein Upgrade Ihrer Verwaltungsdienste auf mindestens Version 2.1.326 durchgeführt.
+
Upgrades mit NetApp Hybrid Cloud Control sind in früheren Service-Bundle-Versionen nicht verfügbar.

* Sie stellen sicher, dass die Systemzeit auf allen Knoten synchronisiert ist und dass NTP für den Speicher-Cluster und die Knoten korrekt konfiguriert ist. Jeder Knoten muss mit einem DNS-Nameserver in der Web-UI pro Knoten konfiguriert werden (`https://[IP address]:442`) ohne ungelöste Clusterfehler im Zusammenhang mit Zeitversatz.
* Sie haben genügend Zeit für Ihr  und link:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["Storage-Firmware"] Upgrades eingeplant.link:task_hcc_upgrade_element_software.html#element-upgrade-time["Element Software"] Bei einem Upgrade auf Element Software 12.5 oder höher variiert die Dauer des Upgradevorgangs je nach Version der Element Software und Firmware-Updates.




== [[sys_Upgrade]]Systemaktualisierungssequenz

Mithilfe der folgenden Sequenz können Sie Ihr NetApp SolidFire All-Flash-Storage-System für Element 12.5 oder höher aktualisieren.

.Schritte
. link:task_hcc_update_management_services.html["Aktualisierung der Managementservices von Hybrid Cloud Control"].
+

IMPORTANT: Wenn Sie Managementservices auf Version 2.16 oder höher aktualisieren und einen Management-Node 11.3 bis 11.8 ausführen, müssen Sie vor der Aktualisierung der Managementservices den RAM der Management-Node-VM erhöhen.

+

IMPORTANT: Vor einem Upgrade der Element Software müssen Sie das neueste Management-Services-Bundle aktualisieren.

. link:task_hcc_upgrade_element_prechecks.html["Integritätsprüfungen von Element Storage vor einem Storage Upgrade durchführen"].
. link:task_hcc_upgrade_element_software.html["Aktualisieren Sie die Element Software und die Storage-Firmware"].
. link:task_hcc_upgrade_storage_firmware.html["(Optional) Aktualisieren Sie nur die Element Storage-Firmware"].
+

NOTE: Möglicherweise führen Sie diese Aufgabe aus, wenn außerhalb einer Hauptversion ein neues Speicher-Firmware-Upgrade verfügbar wird.

. link:task_hcc_upgrade_management_node.html["(Optional) Upgrade Ihres Management-Node"].
+

NOTE: Zum Upgrade der Element Software auf dem Storage-Cluster ist kein Upgrade des Betriebssystems des Management-Node mehr erforderlich. Wenn der Management-Node Version 11.3 oder höher ist, können die Managementservices einfach auf die neueste Version aktualisiert werden, um Element-Upgrades mithilfe von NetApp Hybrid Cloud Control durchzuführen. Befolgen Sie für Ihr Szenario die Vorgehensweise zum Upgrade des Management-Node, wenn Sie aus anderen Gründen, wie z. B. Sicherheitsbehebungsmaßnahmen, ein Upgrade des Betriebssystems des Management-Node durchführen möchten.

. link:task_vcp_upgrade_plugin.html["Aktualisieren Sie Ihr Element Plug-in für vCenter Server"].


[discrete]
== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Dokumentation von SolidFire und Element Software"]

