---
permalink: api/reference_element_api_listclusterinterfacepreferences.html 
sidebar: sidebar 
keywords:  
summary: Mit der ListClusterInterface Preference-Methode können in Storage-Cluster integrierte Systeme, auf denen Element Software ausgeführt wird, die bestehenden Clusterschnittstelleneinstellungen aufgelistet werden, die auf dem System gespeichert sind. Diese Methode ist für den internen Gebrauch bestimmt. 
---
= ListenClusterSchnittstelleneinstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dieser `ListClusterInterfacePreference` Methode können in Storage-Cluster integrierte Systeme mit Element Software die vorhandenen Voreinstellungen für die Cluster-Schnittstelle, die auf dem System gespeichert sind, auflisten. Diese Methode ist für den internen Gebrauch bestimmt.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Einstellungen
 a| 
Eine Liste der aktuell im Storage-Cluster gespeicherten Cluster-Schnittstellenobjekte, die jeweils den Namen und den Wert der Voreinstellungen enthalten.
 a| 
JSON-Objekt-Array

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
	"method": "ListClusterInterfacePreferences",
    "params": {
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
	"id": 1,
	"result": {
		"preferences": [
			{
				"name": "prefname",
				"value": "testvalue"
			}
		]
	}
}
----


== Neu seit Version

11,0
