---
permalink: api/reference_element_api_testkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,testing,test 
summary: 'Mit der TestKeyServerKmip-Methode können Sie testen, ob der angegebene Key Management Interoperability Protocol \(KMIP\)-Schlüsselserver erreichbar und ordnungsgemäß funktioniert.' 
---
= TestKeyServerkmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Methode verwenden `TestKeyServerKmip`, um zu testen, ob der angegebene KMIP-Schlüsselserver (Key Management Interoperability Protocol) erreichbar ist und ordnungsgemäß funktioniert.



[[parameters]]
== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
KeyServer-ID
 a| 
Die ID des zu testenden KMIP-Schlüsselservers.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


[[return-values]]
== Rückgabewerte

Diese Methode hat keine Rückgabewerte. Der Test gilt als erfolgreich, wenn keine Fehler zurückgegeben werden.



[[request-example]]
== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "TestKeyServerKmip",
  "params": {
    "keyServerID": 15
  },
"id": 1
}
----


[[response-example]]
== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
----


[[new-since-version]]
== Neu seit Version

11,7
