---
permalink: api/reference_element_api_listactiveauthsessions.html 
sidebar: sidebar 
keywords: active,sessions,authentication session,list 
summary: Sie können die Methode ListActiveAuthSessions verwenden, um alle aktiven authentifizierten Sitzungen aufzulisten. Diese Methode kann nur von Benutzern mit Administratorrechten verwendet werden. 
---
= ListActiveAuthSessions
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Methode verwenden `ListActiveAuthSessions`, um alle aktiven authentifizierten Sitzungen aufzulisten. Diese Methode kann nur von Benutzern mit Administratorrechten verwendet werden.



[[parameters]]
== Parameter

Diese Methode hat keine Eingabeparameter.



[[return-values]]
== Rückgabewerte

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Sitzungen
 a| 
Sitzungsinformationen für die Authentifizierungssitzungen.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


[[request-example]]
== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "ListActiveAuthSessions"
}
----


[[response-example]]
== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


[[new-since-version]]
== Neu seit Version

12,0
