---
permalink: api/reference_element_api_deletekeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,deleting,delete 
summary: 'Sie können die DeleteKeyProviderKmip-Methode verwenden, um den angegebenen inaktiven Key Management Interoperability Protocol \(KMIP\)-Schlüsselanbieter zu löschen.' 
---
= DeleteKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Methode verwenden `DeleteKeyProviderKmip`, um den angegebenen inaktiven Schlüsselanbieter für das Key Management Interoperability Protocol (KMIP) zu löschen.



== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
ID von Schlüsselausweisungs-ID
 a| 
Die ID des zu löschenden Schlüsselanbieters.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


== Rückgabewerte

Diese Methode hat keine Rückgabewerte. Der Löschvorgang gilt als erfolgreich, solange kein Fehler vorhanden ist.



== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "DeleteKeyProviderKmip",
  "params": {
    "keyProviderID": "1"
    },
"id": 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== Neu seit Version

11,7
