---
permalink: api/reference_element_api_getconfig.html 
sidebar: sidebar 
keywords: node,get,getting,info,config,configuration,getconfig 
summary: Sie können die getconfig API-Methode verwenden, um alle Konfigurationsinformationen für einen Knoten abzurufen. Diese API-Methode umfasst die gleichen Informationen, die sowohl in den API-Methoden GetClusterConfig als auch in GetNetworkConfig verfügbar sind. 
---
= Getconfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mithilfe der `GetConfig` API-Methode alle Konfigurationsinformationen für einen Node abrufen. Diese API-Methode enthält dieselben Informationen, die sowohl in der API- als auch `GetNetworkConfig` in der API-Methode verfügbar `GetClusterConfig` sind.



[[parameters]]
== Parameter

Diese Methode hat keine Eingabeparameter.



[[return-values]]
== Rückgabewerte

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Konfigurations
 a| 
Die Konfigurationsdetails des Clusters. Dieses Objekt enthält:

* xref:reference_element_api_cluster.adoc[Cluster]: Cluster-Informationen, die angeben, wie der Speicher-Node mit dem Speicher-Cluster kommuniziert, mit dem er verknüpft ist.
* xref:reference_element_api_network_all_interfaces.adoc[Netzwerk (alle Schnittstellen)]: Netzwerkverbindungstypen und aktuelle Einstellungen für jede Netzwerkschnittstelle des Knotens.

 a| 
JSON Objekt

|===


[[request-example]]
== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetConfig",
   "params": {},
   "id" : 1
}
----


[[response-example]]
== Antwortbeispiel

Aufgrund der Länge dieses Antwortbeispiels wird es in einem ergänzenden Thema dokumentiert.



[[new-since-version]]
== Neu seit Version

9,6



[[find-more-information]]
== Weitere Informationen

* xref:reference_element_api_getclusterconfig.adoc[GetClusterConfig]
* xref:reference_element_api_getnetworkconfig.adoc[GetNetworkConfig]
* xref:reference_element_api_response_example_getconfig.adoc[Getconfig]

