---
permalink: api/reference_element_api_deleteclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,delete,deleting,DeleteClusterInterfacePreference 
summary: Mit der DeleteClusterInterface Preference-Methode können Systeme, die in Storage-Cluster mit Element Software integriert sind, eine vorhandene Cluster-Schnittstelle löschen. Diese Methode ist für den internen Gebrauch bestimmt. 
---
= DeleteClusterSchnittstellenPräferenz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dieser `DeleteClusterInterfacePreference` Methode können Systeme, die in Storage Cluster mit Element Software integriert sind, eine vorhandene Cluster-Schnittstellenpräferenz löschen. Diese Methode ist für den internen Gebrauch bestimmt.



[[parameters]]
== Parameter

Diese Methode verfügt über den folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Name
 a| 
Der Name der zu löschenden Cluster-Schnittstelle.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.

|===


[[return-values]]
== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



[[request-example]]
== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
	"method": "DeleteClusterInterfacePreference",
	"params": {
		"name": "prefname"
		},
	"id": 1
}
----


[[response-example]]
== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id": 1,
    "result": {}
}
----


[[new-since-version]]
== Neu seit Version

11,0
