---
permalink: api/reference_element_api_getnetworkconfig.html 
sidebar: sidebar 
keywords: network,config,configuration,get,getting,getnetworkconfig 
summary: Sie können die Methode GetNetworkConfig verwenden, um die Netzwerkkonfigurationsinformationen für einen Node anzuzeigen. 
---
= GetNetworkConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `GetNetworkConfig` Methode zum Anzeigen der Netzwerkkonfigurationsinformationen für einen Node verwenden.



[[parameters]]
== Parameter

Diese Methode hat keine Eingabeparameter.



[[return-value]]
== Rückgabewert

Diese Methode hat den folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Netzwerk
 a| 
Verbindungstypen und aktuelle Einstellungen für jede Netzwerkschnittstelle des Nodes.
 a| 
xref:reference_element_api_network_all_interfaces.adoc[Netzwerk (alle Schnittstellen)]

|===


[[request-example]]
== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
   "method": "GetNetworkConfig",
   "params": {},
   "id" : 1
}
----


[[response-example]]
== Antwortbeispiel

Aufgrund der Länge dieses Antwortbeispiels wird es in einem ergänzenden Thema dokumentiert.



[[new-since-version]]
== Neu seit Version

9,6



[[find-more-information]]
== Weitere Informationen

xref:reference_element_api_response_example_getnetworkconfig.adoc[GetNetworkConfig]
