---
permalink: api/reference_element_api_getfipsreport.html 
sidebar: sidebar 
keywords: fips,report,get,getting,getfipsreport,feature,support 
summary: Sie können die GetFipsReport-Methode verwenden, um den Supportstatus der FIPS 140-2-Verschlüsselungsfunktion für alle Nodes im Storage-Cluster zu überprüfen. 
---
= GetFipsReport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Methode verwenden `GetFipsReport`, um den Support-Status der FIPS 140-2-Verschlüsselungsfunktion aller Nodes im Storage-Cluster zu überprüfen.



== Parameter

Diese Methode hat keinen Eingabeparameter.



== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
Ergebnis
 a| 
Ein JSON-Objekt, das den Status von FIPS 140-2-Funktionen für jeden Node unterstützt, und Fehlerinformationen für jeden Node, der nicht auf die Abfrage reagiert hat.
 a| 
xref:reference_element_api_fipsreport.adoc[FipsReport]

|===


== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "GetFipsReport",
  "params": {},
  "id" : 1
}
----


== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id": 1,
    "result": {
    "nodes": [
        {
           "nodeID": 1,
		   "fipsDrives": "None",
           "httpsEnabled": true
        },
        {
           "nodeID": 3,
		   "fipsDrives": "None",
           "httpsEnabled": true
        }
    ],
    "errorNodes": [
        {
           "nodeID": 2,
           "error": {
               "message": "The RPC timed out.",
               "name": "xRpcTimeout"
               }
        }
    ]
    }
}
----


== Neu seit Version

10,3
