---
permalink: api/reference_element_api_testkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,testing,test 
summary: 'Mit der TestKeyProviderKmip-Methode können Sie testen, ob der angegebene Key Management Interoperability Protocol \(KMIP\)-Schlüsselanbieter erreichbar ist und ordnungsgemäß funktioniert.' 
---
= TestKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Methode verwenden `TestKeyProviderKmip`, um zu testen, ob der angegebene KMIP-Schlüsselanbieter (Key Management Interoperability Protocol) erreichbar ist und ordnungsgemäß funktioniert.



[[parameters]]
== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
ID von Schlüsselausweisungs-ID
 a| 
Die ID des zu testenden Schlüsselanbieters.
 a| 
Ganzzahl
 a| 
Keine
 a| 
Ja.

|===


[[return-values]]
== Rückgabewerte

Diese Methode hat keine Rückgabewerte. Der Test gilt als erfolgreich, solange kein Fehler zurückgegeben wird.



[[request-example]]
== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "TestKeyProviderKmip",
  "params": {
    "keyProviderID": 15
  },
"id": 1
}
----


[[response-example]]
== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


[[new-since-version]]
== Neu seit Version

11,7
