---
permalink: api/reference_element_api_createkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,creating,create 
summary: 'Mithilfe der CreateKeyProviderKmip-Methode kann ein Key Management Interoperability Protocol \(KMIP\)-Schlüsselanbieter mit dem angegebenen Namen erstellt werden. Ein Schlüsselanbieter definiert einen Mechanismus und einen Speicherort zum Abrufen von Authentifizierungsschlüsseln. Beim Erstellen eines neuen KMIP-Schlüsselanbieters verfügt dieser über keine KMIP-Schlüsselserver. Verwenden Sie zum Erstellen eines KMIP-Schlüsselservers die CreateKeyServerKmip-Methode. Informationen zum Zuweisen zu einem Provider finden Sie unter AddKeyServerToProviderKmip.' 
---
= CreateKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Methode verwenden `CreateKeyProviderKmip`, um einen KMIP-Schlüsselanbieter (Key Management Interoperability Protocol) mit dem angegebenen Namen zu erstellen. Ein Schlüsselanbieter definiert einen Mechanismus und einen Speicherort zum Abrufen von Authentifizierungsschlüsseln. Beim Erstellen eines neuen KMIP-Schlüsselanbieters verfügt dieser über keine KMIP-Schlüsselserver. Verwenden Sie zum Erstellen eines KMIP-Schlüsselservers die `CreateKeyServerKmip` Methode. Informationen zur Zuordnung zu einem Provider finden Sie unter `AddKeyServerToProviderKmip`.



[[parameters]]
== Parameter

Diese Methode verfügt über die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
SchlüsselProvidername
 a| 
Der Name, der mit dem erstellten KMIP-Schlüsselanbieter verknüpft werden soll. Dieser Name wird nur für Anzeigezwecke verwendet und muss nicht eindeutig sein.
 a| 
Zeichenfolge
 a| 
Keine
 a| 
Ja.

|===


[[return-values]]
== Rückgabewerte

Diese Methode verfügt über die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
KmSchlüsselanbieter
 a| 
Ein Objekt, das Details zum neu erstellten Schlüsselanbieter enthält.
 a| 
link:reference_element_api_keyproviderkmip.html["KeyProviderKmip"]

|===


[[request-example]]
== Anforderungsbeispiel

Anforderungen für diese Methode sind ähnlich wie das folgende Beispiel:

[listing]
----
{
  "method": "CreateKeyProviderKmip",
  "params": {
    "keyProviderName": "ProviderName",
    },
"id": 1
}
----


[[response-example]]
== Antwortbeispiel

Diese Methode gibt eine Antwort zurück, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result":
      {
    "kmipKeyProvider": {
        "keyProviderName": "ProviderName",
        "keyProviderIsActive": true,
        "kmipCapabilities": "SSL",
        "keyServerIDs": [
            15
        ],
        "keyProviderID": 1
    }
}
}
----


[[new-since-version]]
== Neu seit Version

11,7
